[manifest]
version = "1.0.0"
dump_lua = false
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''{file = "resources/fonts/NotoSans-Bold.ttf", render_scale = self.TILESIZE*7, TEXT_HEIGHT_SCALE = 0.65, TEXT_OFFSET = {x=0,y=-40}, FONTSCALE = 0.12, squish = 1, DESCSCALE = 1},'''
position = "at"
payload = '''{file = "resources/fonts/m6x11cyr.ttf", render_scale = self.TILESIZE*10, TEXT_HEIGHT_SCALE = 0.83, TEXT_OFFSET = {x=0,y=0}, FONTSCALE = 0.1, squish = 1, DESCSCALE = 1},'''
overwrite = true
match_indent = true

